name: Upload Creache package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev --system

      - name: Install local packages
        run: pipenv install -e ./src

      - name: Install behave
        run: pip install behave

      - name: Install twine
        run: pip install twine

      - name: Upload using twine
        run: python setup.py sdist && twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

      - name: Increment version
        run: ./increment_version --increment

      - name: Update resources
        uses: EndBug/add-and-commit@v7
        with:
          add: ".version"
