name: Upload Creache package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --dev --system

      - name: Install behave
        run: pip install behave

      - name: Install twine
        run: pip install twine

      - name: Upload using twine
        run: python setup.py sdist && twine upload dist/*
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}

      - name: Increment version
        run: ./increment_version --increment

      - name: Update resources
        uses: test-room-7/action-update-file@v1
        with:
          file-path: .version
          commit-msg: Update resources
          github-token: ${{ secrets.GITHUB_TOKEN }}
